export type Word = {
  /** 画面上の語句 */
  display: string
  /** 実際に打つ文字列。長音の「ー」はハイフン */
  romaji: string
}

/** プログラミングのことば。1試合はこの中から20個を引く。 */
export const WORDS: readonly Word[] = [
  { display: '変数', romaji: 'hensuu' },
  { display: '関数', romaji: 'kansuu' },
  { display: '配列', romaji: 'hairetu' },
  { display: '文字列', romaji: 'mojiretu' },
  { display: '整数', romaji: 'seisuu' },
  { display: '小数点', romaji: 'shousuuten' },
  { display: '条件分岐', romaji: 'joukenbunki' },
  { display: '繰り返し', romaji: 'kurikaesi' },
  { display: '再帰呼び出し', romaji: 'saikiyobidashi' },
  { display: '例外処理', romaji: 'reigashori' },
  { display: '継承', romaji: 'keishou' },
  { display: '抽象クラス', romaji: 'chuushoukurasu' },
  { display: 'インターフェース', romaji: 'inta-fe-su' },
  { display: 'データベース', romaji: 'de-tabe-su' },
  { display: 'アルゴリズム', romaji: 'arugorizumu' },
  { display: 'オブジェクト指向', romaji: 'obujekutoshikou' },
  { display: 'カプセル化', romaji: 'kapuseruka' },
  { display: 'コンパイル', romaji: 'konpairu' },
  { display: 'デバッグ', romaji: 'debaggu' },
  { display: 'リファクタリング', romaji: 'rifakutaringu' },
  { display: 'プルリクエスト', romaji: 'pururikuesuto' },
  { display: 'コミットする', romaji: 'komittosuru' },
  { display: 'ブランチを切る', romaji: 'burantiwokiru' },
  { display: 'マージする', romaji: 'ma-jisuru' },
  { display: '依存関係', romaji: 'izonkankei' },
  { display: '環境変数', romaji: 'kankyouhensuu' },
  { display: '単体テスト', romaji: 'tantaitesuto' },
  { display: '非同期処理', romaji: 'hidoukishori' },
  { display: 'コールバック', romaji: 'ko-rubakku' },
  { display: 'プロミス', romaji: 'puromisu' },
  { display: 'ジェネリクス', romaji: 'jenerikusu' },
  { display: 'スタック', romaji: 'sutakku' },
  { display: 'キュー', romaji: 'kyu-' },
  { display: 'ヒープ', romaji: 'hi-pu' },
  { display: '二分探索', romaji: 'nibuntansaku' },
  { display: 'ハッシュテーブル', romaji: 'hasshute-buru' },
  { display: '計算量', romaji: 'keisanryou' },
  { display: 'ポインタ', romaji: 'pointa' },
  { display: '参照渡し', romaji: 'sanshouwatashi' },
  { display: '値渡し', romaji: 'ataiwatashi' },
  { display: 'ガベージコレクション', romaji: 'gabe-jikorekushon' },
  { display: 'メモリリーク', romaji: 'memoriri-ku' },
  { display: 'デッドロック', romaji: 'deddorokku' },
  { display: '正規表現', romaji: 'seikihyougen' },
  { display: '型推論', romaji: 'katasuiron' },
  { display: 'コンパイルエラー', romaji: 'konpairuera-' },
  { display: 'スタックトレース', romaji: 'sutakkutore-su' },
  { display: 'オーバーフロー', romaji: 'o-ba-furo-' },
  { display: '文字コード', romaji: 'mojiko-do' },
  { display: '初期化', romaji: 'shokika' },
  { display: '一致する', romaji: 'ittisuru' },
  { display: 'マッチする', romaji: 'matti' },
  { display: '認証する', romaji: 'ninshousuru' },
  { display: '公開鍵', romaji: 'koukaikagi' },
  { display: '秘密鍵', romaji: 'himitukagi' },
  { display: '暗号化', romaji: 'angouka' },
  { display: 'フロントエンド', romaji: 'furontoendo' },
  { display: 'バックエンド', romaji: 'bakkuendo' },
  { display: 'コンテナ', romaji: 'kontena' },
  { display: '仮想マシン', romaji: 'kasoumasin' },
  { display: 'git commit', romaji: 'git commit' },
  { display: 'git push', romaji: 'git push' },
  { display: 'null pointer', romaji: 'null pointer' },
  { display: 'async await', romaji: 'async await' },
  { display: 'pull request', romaji: 'pull request' },
]
